# Generated by Django 4.2.4 on 2023-09-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
