# Generated by Django 4.2.4 on 2023-09-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
